server.port=8081
spring.application.name=option

app.allowed-strikes=22900,22950,23000,23050,23100,23150,23200,23250,23300,23350,23400,23450,23500,23550,23600,23650,23700,23750,23800,23850,23900,23950,24000,24050,24100
api.expiry.week=2026-03-17

api.marketsnapshot.stockId=1887
api.marketsnapshot.minTime=9%3A15
api.marketsnapshot.maxTime=15%3A30
api.marketsnapshot.minStrikePrice=22500
api.marketsnapshot.maxStrikePrice=24100

api.trendlyn.url=https://smartoptions.trendlyne.com/phoenix/api/live-oi-data/
api.trendlyn.put.url=https://smartoptions.trendlyne.com/phoenix/api/fno/market/filter/

api.csrf.token=Qy6tuYzXduQOKiOm40AybeBkVom6pYfGq5Yo8qH78DpxECCaBcdxwbmFv998NEIy

api.market.type=options
api.put.screenType=most-active-contract-put
api.call.screenType=most-active-contract-call

# Set a specific package to DEBUG level for more details
logging.level.org.springframework.web=DEBUG

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true

#nifty.cookie.value='_abck=EC0C0DDAD5BB1ACA87A7D8FC76826BFA~-1~YAAQDVM2F+qvwS+bAQAAPddokw+AYkPGlxMHneuynZ7f1hrL5hyWYhNkMC4lWCX2BklJTC6SEU1yjUz/k4zKFj/G5yDd87aGfyQqlXhw5u++eJlK8snVC0GGzcrxwG54gNohvLFOu2oM9Ny9+5X+CtKzFBrmZFwbEgquS4Arkdxrqrxbi8JqJncHgPWLy7oobJNUQAOf/Y4cPgPvfUFt4ru+Fm6AE6E0WYoeVPep0PLmHzXQgzZgAmTJDt9Q0ubhPjIk9yJXFCRKCypCL0204dvxMbQI5Qh0xjAqQvNuRaPTJ+bnJ9rPmET+qBjEva7qGQkJ++vqsiKYl4T2hUtpcefTVKWSsMvlyWXtgcM5CM+WTVoFjLJ5oU2IN7sgQssc19L9nWe4DGoRWxS6pgqcdRzw4+WYZ/HxHlNcMg/TDJX2nOywv9SDu4U9z1Fh2YpPe71pLmhY/bdJuQXHrWTP9N3xr88N~-1~-1~-1~-1~-1; ak_bmsc=42386BE38CD1D44CB5D7310EE2ACEC6B~000000000000000000000000000000~YAAQDVM2F+uvwS+bAQAAPddokx4I+wr/vGhQ0TBDMcREhkCtziYwCj8+hwnc3+1H/tqX/7dgL23cZ6k16pmRqUYAZeYwMuCWcKDxT8PfpWtrBtJBmD4kGAcUCDlwGCEMd8hbxyi2NR21fzUJ1uz5B6wpXRgw6yZrdy6U26JLu4v8hbJfxV8EBxsgSPwgutueAUjbjN1QxvzeeE+1wxScjtLwBa8G3BQ1mDV7nOcf2K5Kiip9B5XO8lf1/KgM6v0Ybe4PRMSq6ZyJsqR+ZzH2ci/9N1dzER+Z45J6YYeIq/wa2x1Ng0HNXDPKCOKa1psz5P6wt4+GC5k9SuUd95hOf7v38uqoSj+MqLHYH9xPXQ==; bm_sv=67B0730935BEEA918A10DCC3F40A3434~YAAQRFM2FwfsXSabAQAAzkF3kx6F21DuOzUubedTtcl5m6pT2u9s5lhbAm0iJESYBougpiCsDChggpeHrv87TmqRJ5p6IrpgLOqlmXgSFYmzd3F/xHD83NH8TqwiqRZ2olAc8w8bzlqH4zork+ACNscVLvsflYFpf+OMX+Cr02ZIjwvupg4k6BDTh+DRNZirju5uRv6+xXnQQ/GcqKNdYDW68URE0o1blBxe8rOUWY/8cBfvsBr6in4mkqH2RbdMt30=~1; bm_sz=F05E881AA5BCB99D8F1E478A13998DFF~YAAQDVM2F+yvwS+bAQAAPddokx6l8gWuFErqP1k5anhVWn9o16OuWW8wO6ENfHuEImE/kHZnAriroQxEENrWDzmaFwzUU/uDQr8E9XWH/v0jEBPO2GHYKmEZgdkr2lFkMKT1jzW8V3k1Q1y6Mgt8aUhpPwe2Cxojc7F6T43DISKBwR0Yjy+/VdNHd65dxtPcPUtlKwOg+sBby3cwEeuWjASmnzDB9P7zX7CnaJSKHFZpVqP4m77wuV2AbUlnlgFyFVJCqRD6PjlR+R1qb1OZmmIp8jT6382911JVueZQlpch80y6B1QLR/FGfbLTXcdd2T9GHBws/K21AfCdvUq/sLMnxXSWrWtjPQjLL3I=~3682628~4471095'
nifty.cookie.value='_abck=EC0C0DDAD5BB1ACA87A7D8FC76826BFA~-1~YAAQDVM2F+qvwS+bAQAAPddokw+AYkPGlxMHneuynZ7f1hrL5hyWYhNkMC4lWCX2BklJTC6SEU1yjUz/k4zKFj/G5yDd87aGfyQqlXhw5u++eJlK8snVC0GGzcrxwG54gNohvLFOu2oM9Ny9+5X+CtKzFBrmZFwbEgquS4Arkdxrqrxbi8JqJncHgPWLy7oobJNUQAOf/Y4cPgPvfUFt4ru+Fm6AE6E0WYoeVPep0PLmHzXQgzZgAmTJDt9Q0ubhPjIk9yJXFCRKCypCL0204dvxMbQI5Qh0xjAqQvNuRaPTJ+bnJ9rPmET+qBjEva7qGQkJ++vqsiKYl4T2hUtpcefTVKWSsMvlyWXtgcM5CM+WTVoFjLJ5oU2IN7sgQssc19L9nWe4DGoRWxS6pgqcdRzw4+WYZ/HxHlNcMg/TDJX2nOywv9SDu4U9z1Fh2YpPe71pLmhY/bdJuQXHrWTP9N3xr88N~-1~-1~-1~-1~-1'